### ISSUE TITLE
Device: (92:53) undefined is not a function (evaluating '_reactNativeAndroidVideoPlayer2.default.play()')

### ISSUE THREAD

**Issue by Angelk90** [scerelli/react-native-android-video-player#3]
@scerelli: I tried the sample code: https://github.com/scerelli/react-native-android-video-player/blob/master/index.android.js

But I get the following error: Device: (92:53) undefined is not a function (evaluating '_reactNativeAndroidVideoPlayer2.default.play ()')

To be able to try it: https://snack.expo.io/B1hLgTAkz

**Comment by scerelli** [comment]
@Angelk90 which version of RN?
