### ISSUE TITLE
react-native build error

### ISSUE THREAD

**Issue by stardevrk** [scerelli/react-native-android-video-player#4]
I have one project now. It uses react-native-android-video-player. 
But It shows following error when I run react-native run-android. Please let me know what is wrong.
~\node_modules\react-native-android-video-player\android\src\main\java\com\reactnativeandroidmediaplayer\mediaplayer\MediaPlayerPackage.java:20: error: method does not override or implement a method from a supertype
    @Override

Thanks

**Comment by scerelli** [comment]
this package is not mantainer anymore i suggest you to switch to https://github.com/react-native-community/react-native-video
